### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ek9** [vdemeester/vcsh-home#4]
Hi,

First, I would like to say thanks for this repository as it has helped me a lot when setting things up and starting with `vcsh` and `mr`. Some time ago I have updated your `bootstrap.sh` and made it into `vcsh-dotfiles` script. I have now pushed it to https://github.com/ek9/vcsh-dotfiles

I have based it on a forked `bootstrap` branch so it has your commits included and I have attributed you as the author for the original script. I would like to publish it via open source lincese (considering MIT at the moment), however as your original repository does not include a license, I am asking you to either add a LICENSE or for permission to license `vcsh-dotfiles` code via MIT or any OSI compatible license.

**Comment by vdemeester** [comment]
@ek9 hey 👋  thanks 😛 
I thought I had a license on that repo but guess not 😉. I'll update real soon (like today) 👼

**Comment by ek9** [comment]
Thanks. Is the license you have picked compatible with MIT? Can I license the code via MIT license and give you attribution?

**Comment by vdemeester** [comment]
@ek9 ah sorry for the delay 😅 Sir yes sir (https://github.com/vdemeester/vcsh-home/blob/master/LICENSE) MIT it is

**Comment by vdemeester** [comment]
(and this can be closed)
